#ifndef MACROS_OF_MY_PROJECT
#define MACROS_OF_MY_PROJECT

#define INSTRUCTION 4
#define INSTRUCTION_SIZE 16
#define ISZ INSTRUCTION_SIZE

#define LOAD 0
#define ADD 1
#define SUB 2
#define STORE 3
#define BUBBLE 4


#endif//MACROS_OF_MY_PROJECT
